import {
  Customer,
  Order,
  SampleDistribution,
  LiquidStockPool,
  PaymentRecord,
  ReturnRecord,
  TimelineEvent,
} from '../src/types/kfos.js';

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Ramesh Super Market',
    businessName: 'Ramesh Super Market',
    place: 'Trichy Main Road',
    phone: '+91 98424 12345',
    outstandingBalance: 1200,
    free200mlSamplesUsed: 1,
    totalOrdersCount: 4,
    totalSpent: 14800,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    isArchived: false,
  },
  {
    id: 'cust-2',
    name: 'Sri Murugan Traders',
    businessName: 'Sri Murugan Departmental',
    place: 'Madurai East',
    phone: '+91 97890 67890',
    outstandingBalance: 0,
    free200mlSamplesUsed: 2,
    totalOrdersCount: 6,
    totalSpent: 28500,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    isArchived: false,
  },
  {
    id: 'cust-3',
    name: 'Annapoorna Hotel & Lodge',
    businessName: 'Annapoorna Hospitality',
    place: 'Chennai Anna Nagar',
    phone: '+91 94431 55432',
    outstandingBalance: 4500,
    free200mlSamplesUsed: 0,
    totalOrdersCount: 2,
    totalSpent: 9000,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    isArchived: false,
  },
  {
    id: 'cust-4',
    name: 'Kashmeer Fragrance Hub',
    businessName: 'Kashmeer Retail Outlet',
    place: 'Coimbatore RS Puram',
    phone: '+91 91234 56789',
    outstandingBalance: 0,
    free200mlSamplesUsed: 2,
    totalOrdersCount: 8,
    totalSpent: 42000,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    isArchived: false,
  },
];

export const SEED_STOCKS: LiquidStockPool[] = [
  {
    quality: 'Eco',
    currentStock5L: 145,
    lowStockThreshold: 30,
    lastRestockedAt: new Date().toISOString(),
  },
  {
    quality: 'Standard',
    currentStock5L: 82,
    lowStockThreshold: 25,
    lastRestockedAt: new Date().toISOString(),
  },
  {
    quality: 'Premium',
    currentStock5L: 48,
    lowStockThreshold: 20,
    lastRestockedAt: new Date().toISOString(),
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'KF-2026-1001',
    customerId: 'cust-1',
    customerName: 'Ramesh Super Market',
    customerPlace: 'Trichy Main Road',
    items: [
      {
        id: 'item-1',
        productVariant: 'Room Freshener',
        quality: 'Eco',
        quantity: 5,
        buyPricePerUnit: 650,
        salePricePerUnit: 900,
        discountPerUnit: 0,
        realizedProfitPerUnit: 250,
        totalAmount: 4500,
        totalProfit: 1250,
      },
    ],
    totalAmount: 4500,
    totalDiscount: 0,
    totalProfit: 1250,
    paidAmount: 3300,
    paymentStatus: 'Partial',
    orderDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    isReturned: false,
    source: 'Telegram Voice',
    isArchived: false,
  },
  {
    id: 'ord-1002',
    orderNumber: 'KF-2026-1002',
    customerId: 'cust-2',
    customerName: 'Sri Murugan Traders',
    customerPlace: 'Madurai East',
    items: [
      {
        id: 'item-2',
        productVariant: 'Bathroom Freshener',
        quality: 'Standard',
        quantity: 10,
        buyPricePerUnit: 750,
        salePricePerUnit: 1200,
        discountPerUnit: 50,
        realizedProfitPerUnit: 400,
        totalAmount: 11500,
        totalProfit: 4000,
      },
    ],
    totalAmount: 11500,
    totalDiscount: 500,
    totalProfit: 4000,
    paidAmount: 11500,
    paymentStatus: 'Paid',
    orderDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    isReturned: false,
    source: 'Telegram Text',
    isArchived: false,
  },
];

export const SEED_SAMPLES: SampleDistribution[] = [
  {
    id: 'samp-1',
    customerId: 'cust-1',
    customerName: 'Ramesh Super Market',
    sampleType: '200ml',
    isFree: true,
    quantity: 1,
    chargeAmount: 0,
    profit: 0,
    distributedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    followUpDueDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    followUpStatus: 'Pending',
    followUpNotes: 'Check if they liked the Premium Rose aroma for hotel lobby.',
  },
  {
    id: 'samp-2',
    customerId: 'cust-3',
    customerName: 'Annapoorna Hotel & Lodge',
    sampleType: '500ml',
    isFree: false,
    quantity: 1,
    chargeAmount: 300,
    profit: 0,
    distributedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    followUpDueDate: new Date().toISOString(),
    followUpStatus: 'Pending',
    followUpNotes: 'Follow up on 500ml test trial in 10 luxury suits.',
  },
];

export const SEED_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    orderId: 'ord-1001',
    customerId: 'cust-1',
    customerName: 'Ramesh Super Market',
    amount: 3300,
    paymentMethod: 'UPI',
    receivedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: 'Advance against order KF-2026-1001',
  },
  {
    id: 'pay-2',
    orderId: 'ord-1002',
    customerId: 'cust-2',
    customerName: 'Sri Murugan Traders',
    amount: 11500,
    paymentMethod: 'Cash',
    receivedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: 'Full payment collected on delivery',
  },
];

export const SEED_RETURNS: ReturnRecord[] = [];

export const SEED_TIMELINE: TimelineEvent[] = [
  {
    id: 'time-1',
    timestamp: new Date().toISOString(),
    type: 'Order Created',
    title: 'Order KF-2026-1002 Placed',
    description: '10 Cans of Standard Bathroom Freshener ordered by Sri Murugan Traders.',
  },
];
